apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: volume-claim
  namespace: hmedel
spec: 
  storageClassName: sistemafichero
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi